services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $projectDir: '%kernel.project_dir%'
            $zip: '@markocupic.zip_bundle.zip.zip'

    Markocupic\ContaoBundleCreatorBundle\:
        resource: ../src/
        exclude: ../src/{DependencyInjection,Model,Event}


